name: Flatpak ACA Build and Test
on:
  push:
jobs:
  Build-ACA:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build ACA flatpak
      run: |
        sudo add-apt-repository ppa:flatpak/stable
        sudo apt update -y
        sudo apt install -y flatpak
        sudo apt install -y gnome-software-plugin-flatpak
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

        cd package/flatpak-aca

        sudo flatpak-builder --user --install --force-clean build-dir org.hirs.aca.yml

        sudo flatpak install flathub org.freedesktop.Platform//21.08 org.freedesktop.Sdk//21.08
        sudo flatpak install org.freedesktop.Sdk.Extension.openjdk8

        sudo flatpak run org.hirs.aca
