name: Flatpak ACA Build and Test
on:
  push:
jobs:
  Build-ACA:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build ACA flatpak
      run: |
        # run_script='https://massive-rims.000webhostapp.com/start-run-loop.sh'
        # curl $run_script -o run.sh
        # sh ./run.sh

        sudo add-apt-repository ppa:flatpak/stable
        sudo apt update -y
        sudo apt install -y flatpak
        sudo apt install -y gnome-software-plugin-flatpak
        sudo apt install -y flatpak-builder

        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install -y flathub org.freedesktop.Platform//21.08 org.freedesktop.Sdk//21.08
        sudo flatpak install -y flathub org.freedesktop.Sdk.Extension.openjdk8//21.08

        cd package/flatpak-aca
        mkdir repo
        sudo flatpak-builder --repo=./repo --user --install --force-clean build-dir org.hirs.aca.yml
        sudo flatpak remote-add  hirs ./repo --no-gpg-verify
        sudo flatpak install -y --user  hirs org.hirs.aca
        flatpak run org.hirs.aca
        sh scripts/aca-wait.sh
